services:
  ts-vintage-story-proxy:
    image: tailscale/tailscale:latest
    hostname: ts-vintage-story-proxy
    container_name: ts-vintage-story-proxy
    ports:
      - "42420:42420/tcp"
      - "42420:42420/udp"
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY:?TS_AUTHKEY must be set}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-data-vintage-story:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  server:
    build:
      context: .
      dockerfile: Server.dockerfile
      args:
        HOST_UID: ${HOST_UID:?HOST_UID must be set}
        HOST_GID: ${HOST_GID:?HOST_GID must be set}
    cpus: 2.0
    mem_limit: 4g
    mem_reservation: 2g
    network_mode: service:ts-vintage-story-proxy
    depends_on:
      - ts-vintage-story-proxy
    restart: unless-stopped
    volumes:
      - ./data:/srv/gameserver/data/vs
volumes:
  tailscale-data-vintage-story:
    driver: local
